tasks:
  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    command: |
      npm install
      gp open README.md

vscode:
  extensions:
    - https://github.com/synedra/katapod/releases/download/0.1.4/katapod-0.1.4.vsix
